version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes"
      - terraform plan -out=tfplan.binary
      - terraform show -json tfplan.binary > tfplan.json

  post_build:
    commands:
      - echo "Applying Terraform changes if approved"
      - terraform apply -auto-approve tfplan.binary
