version: 0.2

env:
  variables:
    API_GATEWAY_URL: "https://pnrcwo0qki.execute-api.us-east-1.amazonaws.com/dev/math"

phases:
  install:
    runtime-versions:
      terraform: 1.5.7
    commands:
      - echo "Installing dependencies"
      - |
        if command -v yum > /dev/null 2>&1; then
          yum install -y jq aws-cli
        elif command -v apt-get > /dev/null 2>&1; then
          apt-get update
          apt-get install -y jq awscli
        elif command -v apk > /dev/null 2>&1; then
          apk add --no-cache jq aws-cli
        else
          echo "Package manager not supported"
          exit 1
        fi
      - jq --version
      - echo "Installing Terraform"
      - terraform --version
      - echo "Retrieving GitHub OAuth token from Secrets Manager..."
      - |
        SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id oauth_token --query SecretString --output text)
        GITHUB_TOKEN=$(echo $SECRET_VALUE | jq -r '.oauth_token')
        if [ -z "$GITHUB_TOKEN" ]; then 
          echo "Error: GitHub token is empty"
          exit 1
        fi
        echo "GitHub token retrieved successfully"
        export GITHUB_TOKEN

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes"
      - terraform plan -out=tfplan.binary -var="oauth_token=${GITHUB_TOKEN}"
      - terraform show -json tfplan.binary > tfplan.json

  post_build:
    commands:
      - echo "Applying Terraform changes if approved"
      - terraform apply -auto-approve tfplan.binary
























# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       terraform: 1.5.7
#     commands:
#       - echo "Installing dependencies"
#       - yum install -y jq aws-cli
#       - echo "Installing Terraform"
#       - terraform --version
#       - echo "Retrieving GitHub OAuth token from Secrets Manager..."
#       - |
#         GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github-oauth-token --query SecretString --output text | jq -r '.github_oauth_token')
#         if [ -z "$GITHUB_TOKEN" ]; then 
#           echo "Error: GitHub token is empty"
#           exit 1
#         fi
#         echo "GitHub token retrieved successfully"
#         export GITHUB_TOKEN

#   pre_build:
#     commands:
#       - echo "Initializing Terraform"
#       - terraform init

#   build:
#     commands:
#       - echo "Planning Terraform changes"
#       - terraform plan -out=tfplan.binary -var="oauth_token=${GITHUB_TOKEN}"
#       - terraform show -json tfplan.binary > tfplan.json

#   post_build:
#     commands:
#       - echo "Applying Terraform changes if approved"
#       - terraform apply -auto-approve tfplan.binary
