name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      apply_plan:
        description: 'Would you like to terraform apply? (yes/no)'
        required: true
        default: 'no'
        type: string

permissions:
  contents: write  # Allows GitHub Actions to push changes to the repository
  actions: write   # Allows GitHub Actions to trigger actions

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_oauth_token: ${{ secrets.OAUTH_TOKEN }}

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan.binary
          path: tfplan.binary

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: ${{ github.event.inputs.apply_plan == 'yes' }}  # Check if 'apply_plan' is 'yes'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Apply
        run: terraform apply tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
