name: Terraform Workflow
 
on:
  workflow_dispatch:
    inputs:
      apply_plan:
        description: 'Would you like to terraform apply? (yes/no)'
        required: true
        default: 'no'
        type: string
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.OAUTH_TOKEN }}
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.0
 
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
    - name: Terraform Init
      run: terraform init -backend-config=backend.hcl
      working-directory: ./infrastructure
 
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./infrastructure
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_oauth_token: ${{ secrets.OAUTH_TOKEN }}
 
    - name: Terraform Apply
      if: ${{ github.event.inputs.apply_plan == 'yes' }}
      run: terraform apply -auto-approve
      working-directory: ./infrastructure
