name: Terraform CI/CD

on:
  push:
    branches:
      - dev  # Trigger workflow on pushes to the dev branch
  pull_request:
    branches:
      - main  # Optional: Trigger workflow on pull requests to main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 4: Terraform Plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan.binary
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_oauth_token: ${{ secrets.OAUTH_TOKEN }}

    # Step 5: Upload Plan for Approval
    - name: Upload Plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan.binary
        path: tfplan.binary

    # Step 6: Wait for Manual Approval
    - name: Request Approval
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: terraform-apply-approval
        client-payload: '{"plan_url": "${{ steps.plan.outputs.plan-file-url }}"}'

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [terraform]
    if: ${{ github.event.client_payload.event_type == 'terraform-apply-approval' }}

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # Step 3: Apply Terraform Plan
    - name: Terraform Apply
      run: terraform apply tfplan.binary
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
