name: Terraform CI/CD

on:
  push:
    branches:
      - dev  
jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_oauth_token: ${{ secrets.OAUTH_TOKEN }}

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan.binary
          path: tfplan.binary

      - name: Request Approval
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: terraform-apply-approval
          client-payload: '{"plan_url": "${{ steps.plan.outputs.plan-file-url }}"}'
          token: ${{ secrets.OAUTH_TOKEN }}  # Use the Personal Access Token stored in GitHub Secrets
          repository: Bhavana0918/POMP-IAC-TERRAFORM

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ github.event.client_payload.event_type == 'terraform-apply-approval' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
